version: '3.8'
services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/team-roles-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres:latest
    container_name: team-roles-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=team-roles-db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/datah
  db-test:
    image: postgres:latest
    container_name: team-roles-db-test
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=team-roles-db-test
    ports:
      - '5436:5432'
    volumes:
      - db:/var/lib/postgresql/datag
volumes:
  db: